site_name: LT CS Study Notes
site_url: https://louiskwt.github.io/teach-myself-cs/
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.instant
    - navigation.instant.progress

nav:
  - Home: index.md
  - "MIT 6.100":
      - "6.100/index.md"
      - "6.100/lecture1.md"
